### ISSUE TITLE
small detail

### ISSUE THREAD

**Issue by DragonLord7791** [LightningMods/Itemzflow#11]
when i rebuild internal database the fix for app2usb hes apply just to 1 external drive
any idea why ?

**Comment by LightningMods** [comment]
The rebuild internal database option only rebuilds the database for the Internal HDD, if you use app2usb it technically should work assuming all USBs with those game are plugged in, if it doesnt work as is for app2usb I wont bother fixing it since everyone should be using Sony's Official External HDD feature (added in 4.55??) for storing games on external USB drives

**Comment by DragonLord7791** [comment]
Why then did you put the option Move to usb and restore to usb ? if the links are broken do the rebuild doesn't work. You should fix it because you put the option move to usb and restore from usb. If I do move to usb it would be the same function as app2usb. Fix it because your app itemzflow has the same function as app2usb

**Comment by DragonLord7791** [comment]
Why then did you put the option Move to usb and restore to usb ? if the
links are broken do the rebuild doesn't work. You should fix it because you
put the option move to usb and restore from usb. If I do move to usb it
would be the same function as app2usb. Fix it because your app itemzflow
has the same function as app2usb
