### ISSUE TITLE
Option to rebuild dlc causes theme issues

### ISSUE THREAD

**Issue by KartikKurt** [LightningMods/Itemzflow#20]
In my ps4 pro, the games which are on extended storage doesn't show their DLC. So i used itemzflow game manager's option to rebuild only dlc as it would fix the missing extended storage DLCs. It fixed and the DLCs were visible again but my permanent themes were gone now. As soon as i reboot my console, the dlcs were missing again and the themes were not showing up in storage settings.
![20230725_200845](https://github.com/LightningMods/Itemzflow/assets/140532275/8fafe282-29f0-4132-a49e-09e46c6e68b3)
![20230725_202257](https://github.com/LightningMods/Itemzflow/assets/140532275/7fe2b2b2-44ee-4d33-99ca-a2a3c1a1fbf2)

**Comment by LightningMods** [comment]
When using an external storage drive you may need to re-activate the DLCs every reboot (Internal HDD doesn't have this issue iirc)  which is why we added the "Re-activate ext. Content" option in the rebuild db options (3rd option), you may not see your themes as Itemzflow currently doesn't support themes when rebuilding the database (which is why the option desc doesn't mention themes), If I was to add theme support are you available to test?

**Comment by LightningMods** [comment]
I will close this request in 2 days for inactivity if there is no response

**Comment by LightningMods** [comment]
This issue has been closed due to inactivity
