### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by Gilles89a** [LightningMods/Itemzflow#41]
Dumping can take a long time (more than 8 hours, and sometimes far longer) especially when thousands of small files have to copied. An option to create an ISO instead of copying everything immediately could maybe help to speed up the dumping process significantly, in my opinion. 
Would that be an option?

**Comment by Izofeu** [comment]
You still have to write the iso file somewhere first, and then make an fpkg out of all the files. You also need all the individual files to generate a GP4 file. In your case I'd say the issue is the USB drive. I use a USB->SATA adapter and connect a 3.5" HDD to the ps4. Dumping is super fast, I think it took around half an hour for a 35GB game with GP4 generation? Or maybe a bit longer, but definitely under an hour and that's WAY under 8 hours.

**Comment by LightningMods** [comment]
making an ISO wont help make it any faster as you would need to add all those small files to the ISO too, also I have never seen a game even with thousands of small files take more than 2 hours and I have tested it, you should try either dump to the internal storage or get a better USB to increase speeds

**Comment by Gilles89a** [comment]
No, that is not what i meant, i am aware on how to produce fpkgs and gp4. Transferring thousands of files individually to a USB i a very slow, always. Collecting all files in a single iso (or zip, it doesn't matter) before transferring it to an usb would be much faster i think. From there it could be unpacked and processed further. 
Of course, this highly depends on the game. I dumped games with 50 gb very quickly, around the time you mentioned, but others with thousands of small files take hours and hours. "Pillars of Eternity Deadfire" is an example for that.

**Comment by Gilles89a** [comment]
> making an ISO wont help make it any faster as you would need to add all those small files to the ISO too, also I have never seen a game even with thousands of small files take more than 2 hours and I have tested it, you should try either dumping to the internal storage or get a better USB to increase speeds

Just noticed your reply now after my answer. I'm using highspeed usb stick that worked very fast with "normal" games, but Deadfire took 8 hours before I canceled it after 8 hours.

**Comment by Gilles89a** [comment]
Oh, closed already. Okay :)

**Comment by LightningMods** [comment]
I will test "Pillars of Eternity Deadfire" on my PS4 with my USB and see how long it takes, also while copying 1 large file would be faster than thousands of small files you gotta remember there is still overhead for adding thousands of small files to an ISO or Zip which will likely add more time because you have to archive/build then transfer it, a better idea would be to just copy the PFS image and extracting it on PC

**Comment by Gilles89a** [comment]
Thanks for your clarification :)

I'll try it again tomorrow dumping to the internal storage as you suggested.

**Comment by LightningMods** [comment]
Hello I dumped the base game of "Pillars of Eternity 2 Deadfire" to internal storage (/data) and it only took me 143 mins, I will see if I can slightly improve the time tho 
![My Great Game - My Great Capture_2024-06-17_01-00-36](https://github.com/LightningMods/Itemzflow/assets/34066913/85d04e71-fb2d-406e-979e-0eb4c37dd3d8)

**Comment by Gilles89a** [comment]
Thanks for the feedback! I retried it too using the internal storage as dump target, then the dumping time was around 140 minutes as well. I think it's save to say now that the problem is on my USB device. It's a USB 3.1 stick, but transfer rates are extremely slow, so i guess the device is damaged. Apologies, i should have checked that before opening an issue!

Btw, when using option "Dump all", itemzflow processes the base game, then asks me for gp4 (i usually reject that) and then, when dumping the patch, there is no progress bar, until after some minutes the gp4 question comes up for the patch. Everything seems to work fine, though.

Again, thank you very much for your help!

-------- Ursprüngliche Nachricht --------
Am 17.06.24 07:04 um LM schrieb :
