### ISSUE TITLE
Game dump halts partway through

### ISSUE THREAD

**Issue by peterwankman** [LightningMods/Itemzflow#45]
This happens to me when trying to dump CUSA18278 (Cyberpunk 2077)

I have the game installed on internal HDD with all retail patches installed (1.61).
When using "Dump all", the progress halts at 
/mnt/usb0/CUSA18278//archive/ps4/content/lang_de_voice.archive 66%
and doesn't progress any further, even after several hours.

This happens on two separate PS4 systems.

**Comment by walterman105** [comment]
I'm also having this issue on an old build of Fortnite (CUSA07022)
I've tried "Dump All" and "Dump Base Only" and it gets stuck on
/mnt/usb0/CUSA07022//fortnitegame/content/paks/pakchunk2-ps4client.pak 93%

I've tried it 4 times and left it on for a few hours and it gets stuck every time. I've tried it with 2 external drives, a 64GB SSD and 1TB HDD same issue. As far as I can tell the drive just stops being accessed at this step.

**Comment by LightningMods** [comment]
The readme mentions this, this is nothing new, even in modded warfare's tutorials he mentions this

https://github.com/LightningMods/Itemzflow?tab=readme-ov-file#dumper-details

If you read the readme you would know it gets stuck on files that are not installed like additional language packs, in your own comment you mention it gets stuck on a DE language file `lang_de_voice.archive` as a result this issue is now closed

**Comment by OliKosch** [comment]
Just an additional question, b/c stuck on Hogwarts Legacy patch: how can one install these missing files? The base game was back-upped without problems. Every help is greatly appreciated.
