### ISSUE TITLE
Responsible for breaking REST MODE; Apollo, Orbis toolbox, itemzFlow, HomeBrew Store

### ISSUE THREAD

**Issue by jason-eu** [LightningMods/Itemzflow#77]
[https://twitter.com/Kameleonre_/status/1850768786833490260]()

![Screenshot_2024-10-28-08-34-15-362_com.twitter.android-edit.jpg](https://github.com/user-attachments/assets/1125506d-ec47-4f4c-a2e1-9d7c9abc7ae6)

**Comment by LightningMods** [comment]
feel free to submit a PR, otherwise this issue is closed

**Comment by jason-eu** [comment]
Clearly.

**Comment by LightningMods** [comment]
I also want to mention that I dont think this issue is an itemzflow issue, notice how rest mode works fine on 9.00 or below with itemzflow, but feel free to look at the code and try to find whatever they think causes this issue, notice how they didnt give any explanation either besides "rest mode is broken must be the Homebrew apps" and considering it effects other HB like apollo too this is very likely not an issue with the apps themselves
